dataset:
  dataset_type: "static"
  sample_rate: 16000
  segment_seconds: 2.0
  root_dir: "/disk2/bywang/DOA-net/data/librispeech_cipic_multisubject_robust50h_v1/train_subjects"
  train_root: "/disk2/bywang/DOA-net/data/librispeech_cipic_multisubject_robust50h_v1/train_subjects"
  val_root: "/disk2/bywang/DOA-net/data/librispeech_cipic_multisubject_robust50h_v1/val_subjects"
  test_root: "/disk2/bywang/DOA-net/data/librispeech_cipic_multisubject_robust50h_v1/test_subjects_unseen"
  split_seed: 42

feature:
  n_fft: 512
  hop_length: 160
  win_length: 400
  window: "hann"

model:
  type: "bil_style_gccphat_crn_72cls"
  bil_gcc_bins: 64
  bil_cnn_channels: [32, 64, 96]
  bil_f_pool_size: [2, 2, 2]
  bil_t_pool_size: [1, 1, 1]
  bil_kernel_size: [3, 3]
  bil_gru_hidden_size: 96
  bil_gru_num_layers: 1
  bil_bidirectional: true
  bil_mlp_hidden_size: 128
  num_classes: 72
  azimuth_range: [-180, 180]
  dropout: 0.1
  use_front_back_auxiliary: false

train:
  batch_size: 64
  num_workers: 8
  device: "cuda"

output:
  save_dir: "outputs/checkpoints_multisubject_robust50h_bilstyle_gccphat_crn72_seennoise_eval"
  log_dir: "outputs/logs_multisubject_robust50h_bilstyle_gccphat_crn72_seennoise_eval"
