dataset:
  root_dir: "/disk2/bywang/DOA-net/data/librispeech_cipic_multisubject_robust50h_v1/train_subjects"
  train_root: "/disk2/bywang/DOA-net/data/librispeech_cipic_multisubject_robust50h_v1/train_subjects"
  val_root: "/disk2/bywang/DOA-net/data/librispeech_cipic_multisubject_robust50h_v1/val_subjects"
  test_root: "/disk2/bywang/DOA-net/data/librispeech_cipic_multisubject_robust50h_v1/test_subjects_unseen"
  sample_rate: 16000
  segment_seconds: 2.0
  split_seed: 42
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15

feature:
  n_fft: 512
  hop_length: 160
  win_length: 400
  window: "hann"

model:
  type: "native_lite_v7_dual_cue_concat"
  encoder_variant: "v2_balanced"
  content_input_mode: "logmag"

  encoder_channels: [24, 40, 64]
  encoder_out_dim: 96

  content_relation_mode: "mean_diff_absdiff"
  content_fusion_dim: 80

  lite_cue_bands: 16
  lite_cue_hidden_dim: 48
  cue_value_out_dim: 24
  cue_reliability_out_dim: 8
  lite_cue_kernel_size: 3
  lite_cue_encoder_type: "temporal_conv"
  dual_cue_fusion_mode: "concat"
  dual_cue_use_tf_mask: true
  dual_cue_tf_mask_hidden_channels: 8
  dual_cue_tf_mask_residual_scale: 1.0

  use_cross_ear_interaction: false
  temporal_encoder_type: "gru"
  gru_hidden_size: 80
  gru_num_layers: 1
  gru_dropout: 0.1

  num_classes: 72
  azimuth_range: [-180, 180]
  dropout: 0.2

  use_front_back_auxiliary: true
  use_attention_pooling: true
  use_regression: false
  use_pure_regression: false

train:
  batch_size: 64
  num_workers: 8
  epochs: 100
  lr: 0.0005
  weight_decay: 0.0001
  label_smoothing: 0.1
  scheduler: "cosine"
  cosine_T_max: 100
  cosine_eta_min: 0.00001
  amp: false
  device: "cuda"
  grad_clip: 1.0

  anti_confusion_weight: 0.0
  circular_soft_label_weight: 0.0
  front_back_aux_weight: 0.3

  log_interval: 50
  val_interval: 1
  early_stopping_patience: 15

output:
  save_dir: "outputs/checkpoints_multisubject_robust50h_v7_dualcue_vr_tfmask_cf80_gru80_nocsl_fbaux_cohfix"
  log_dir: "outputs/logs_multisubject_robust50h_v7_dualcue_vr_tfmask_cf80_gru80_nocsl_fbaux_cohfix"
