dataset:
  root_dir: "/disk2/bywang/DOA-net/data/librispeech_cipic_roomsim25_v1/train"
  train_root: "/disk2/bywang/DOA-net/data/librispeech_cipic_roomsim25_v1/train"
  val_root: "/disk2/bywang/DOA-net/data/librispeech_cipic_roomsim25_v1/val"
  test_root: "/disk2/bywang/DOA-net/data/librispeech_cipic_roomsim25_v1/test"
  sample_rate: 16000
  segment_seconds: 2.0
  split_seed: 42

feature:
  n_fft: 512
  hop_length: 160
  win_length: 400
  window: "hann"

model:
  type: "dprtf_doa_cls"
  dprtf_template_path: "data/dprtf_templates/rtf_dp_cipic25_train30_mean_16k.mat"
  dprtf_freq_bins_used: 128
  dprtf_planes: 64
  dprtf_rnn_hidden_size: 256
  dprtf_use_residual_blocks: false
  num_classes: 25
  azimuth_range: [-180, 180]
  class_angles_deg: [-80, -65, -55, -45, -40, -35, -30, -25, -20, -15, -10, -5, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 55, 65, 80]
  dropout: 0.2
  use_front_back_auxiliary: false

train:
  batch_size: 32
  num_workers: 8
  epochs: 100
  lr: 0.0005
  weight_decay: 0.0001
  label_smoothing: 0.0
  scheduler: "cosine"
  cosine_T_max: 100
  cosine_eta_min: 0.00001
  amp: false
  device: "cuda:0"
  grad_clip: 1.0
  anti_confusion_weight: 0.0
  circular_soft_label_weight: 0.0
  front_back_aux_weight: 0.0
  front_back_focus_weight: 0.0
  log_interval: 50
  val_interval: 1
  early_stopping_metric: "mae"
  early_stopping_patience: 15
  early_stopping_min_delta: 0.01

output:
  save_dir: "outputs/checkpoints_cipic_roomsim25_v1_dprtf_trainmean_bestmae_seed42_phys3"
  log_dir: "outputs/logs_cipic_roomsim25_v1_dprtf_trainmean_bestmae_seed42_phys3"
